// <auto-generated />
namespace ArtMin.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AjustcolunaCPF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjustcolunaCPF));
        
        string IMigrationMetadata.Id
        {
            get { return "202009121841524_Ajust coluna CPF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
