// <auto-generated />
namespace ArtMin.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InclusaodecolunaCPF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InclusaodecolunaCPF));
        
        string IMigrationMetadata.Id
        {
            get { return "202009121838225_Inclusao de coluna CPF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
